import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.text.AbstractDocument;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.AttributeSet;

/**
 * The EmployeeSubmit class represents the panel for submitting an order.
 * This panel allows employees to enter the customer's name and their own employee ID to submit an order.
 */
public class EmployeeSubmit extends JPanel {
    private JTextField nameField;
    private JTextField IDField;
    private JButton submitButton;
    private JButton backButton;

    /**
     * Constructs a new EmployeeSubmit panel.
     * This method initializes the layout and components of the submit panel.
     */
    public EmployeeSubmit() {
        setLayout(new BorderLayout());

        JLabel label = new JLabel("Enter a name for the order");
        add(label, BorderLayout.NORTH);

        JPanel submitScreen = new JPanel();
        submitScreen.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        // NAME INPUT
        // Add label for name input
        JLabel nameLabel = new JLabel("Name:");
        submitScreen.add(nameLabel);
        // Add text field for name input
        nameField = new JTextField(20);
        submitScreen.add(nameField);

        // ID input
        // Add label for ID input
        JLabel IDLabel = new JLabel("Employee ID:");
        submitScreen.add(IDLabel);
        // Add text field for ID input
        IDField = new JTextField(20);
        limitInputToNumeric(IDField);
        submitScreen.add(IDField);

        // Create submit and back buttons and add them to the submitScreen panel
        submitButton = new JButton("Submit");
        submitButton.setPreferredSize(new Dimension(150, 70));
        submitButton.setFont(new Font("Arial", Font.PLAIN, 25));
        submitScreen.add(submitButton);

        backButton = new JButton("Back");
        backButton.setPreferredSize(new Dimension(150, 70));
        backButton.setFont(new Font("Arial", Font.PLAIN, 25));
        submitScreen.add(backButton);

        add(submitScreen, BorderLayout.CENTER);

        // Add action listeners to the buttons
        submitButton.addActionListener(new ButtonClickListener(this, "Submit"));
        backButton.addActionListener(new ButtonClickListener(this, "Back"));
    }

    /**
     * The ButtonClickListener class represents an action listener for submit and back buttons.
     * This class handles the actions performed when the buttons are clicked.
     */
    private class ButtonClickListener implements ActionListener {
        private EmployeeSubmit employeeSubmit;
        private String buttonName;

        /**
         * Constructs a new ButtonClickListener object.
         * @param employeeSubmit The EmployeeSubmit panel associated with the listener.
         * @param buttonName The name of the button associated with the listener.
         */
        public ButtonClickListener(EmployeeSubmit employeeSubmit, String buttonName) {
            this.employeeSubmit = employeeSubmit;
            this.buttonName = buttonName;
        }

        /**
         * Handles the actions performed when the buttons are clicked. If the submit button was 
         * clicked, and there are no problems, the order is submitted and the main employee 
         * screen is loaded. If the back button was clicked, the main employee screen is loaded 
         * without submitting the order.
         * @param e The action event generated by clicking the button.
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            if (buttonName.equals("Submit")) {
                // Check if name field is empty
                if (nameField.getText().isEmpty() || IDField.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(employeeSubmit, "Please enter a name and employee ID for the order.", "Error", JOptionPane.ERROR_MESSAGE);
                } 
                else {
                    int employeeID = Integer.parseInt(IDField.getText());
                    boolean success = Employee.empCmds.submitOrder(Employee.selectedMenuIDs, nameField.getText(), employeeID);
                    if(!success) {
                        JOptionPane.showMessageDialog(employeeSubmit, "There was an error processing the order, please contact a manager", "Error", JOptionPane.ERROR_MESSAGE);
                    }
        
                    // Clear out selectedMenuIDs
                    Employee.selectedMenuIDs.clear();
                    // Close the frame
                    SwingUtilities.getWindowAncestor(EmployeeSubmit.this).dispose();
                    // Removes buttons and repaints
                    Employee.upperOrderPanel.removeAll();
                    // Reset price
                    Employee.update();
                }
            } else if (buttonName.equals("Back")) {
                    // Handle back action
                    // Close the frame
                    SwingUtilities.getWindowAncestor(EmployeeSubmit.this).dispose();
            }
        }
    }

    /**
     * Limits the input of a text field to numeric characters only.
     * @param textField The text field to which the input restriction is applied.
     */
    private static void limitInputToNumeric(JTextField textField) {
        AbstractDocument document = (AbstractDocument) textField.getDocument();
        document.setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr)
                    throws BadLocationException {
                if (string.matches("-?\\d*")) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                if (text.matches("-?\\d*")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }
}
